name: Jest Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install modules
        run: yarn
      - name: Run Jest
        run: yarn workspace server test
